### ISSUE TITLE
Output Errors when Formatting isn't Possible

### ISSUE THREAD

**Issue by HolyShaq** [Gidsss/UwUIDE#240]

**Comment by am-cid** [comment]
Can you describe what's making it impossible?

**Comment by am-cid** [comment]
The question is why. Why are we squiggly lining? Cant we just show the lexer/parser errors like usual? (without the token list and ast)

**Comment by am-cid** [comment]
The reason for the question is the inconsistency. Is formatting the only place the squiggly lines will be implemented or will it be for all errors?

**Comment by HolyShaq** [comment]
> The question is why. Why are we squiggly lining? Cant we just show the lexer/parser errors like usual?

Thinking about it now, I think this might be better actually. Those errors have more useful context anyways. It slipped my mind hahahaha

**Comment by chaaals** [comment]
@HolyShaq @am-cid I suggested yung squiggly lines because I thought ang context lang niya is nasa code editor/text widget since we're autoformatting and no need to provide more context sa user, sorry!

Pero sige mas madali i-implement if diretso compiler error table. Mas maganda sana flow if from compile and run tska nag a-autoformat kaso blocked ng token highlighting.

**Comment by HolyShaq** [comment]
Oki, I will change the issue to that then. Push ako PR by tonight, thanks!

**Comment by am-cid** [comment]
merged #238, closing this
